name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 * * # once a month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repos
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag axsl:$(date +%s)
