name: test

on: [push, workflow_dispatch]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      OPAMCONFIRMLEVEL: yes
      OPAMVERBOSE: 4

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup opam
        run: |
          bash -c "echo | sh <(curl -L https://opam.ocaml.org/install.sh)"
          opam init --disable-sandboxing

      - name: build AxSL dependencies
        run: |
          eval $(opam env --switch=default)

          opam repo add coq-released https://coq.inria.fr/opam/released
          opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git

          opam pin coq-iris 4.2.0
          opam install coq-iris coq-hammer-tactics coq-record-update

          git clone https://github.com/rems-project/coq-sail
          cd coq-sail/
          git checkout f749632
          opam pin .
          cd ..

          git clone https://github.com/tchajed/iris-named-props
          cd iris-named-props/
          git checkout 3cf2d97
          opam pin .
          cd ..

      - name: build AxSL
        run: |
          eval $(opam env --switch=default)
          dune build --display=verbose

